# Generated by Django 6.0 on 2025-12-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_employee_employees_alter_employees_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
