# Generated by Django 6.0.2 on 2026-03-10 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_stafff',
            new_name='is_staff',
        ),
    ]
