"""
Django settings for ch48 project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&_zdn_5jb&%io31cx#k-ohr&f)ar)%9@zdq9!$*6ent6=u_19l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ch48.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ch48.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'blog_postgres' :{
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',
        'PORT': '5432',
    }

}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
LOGGING = {
    'version':1,
    'disble_existing_loggers':False, # becasuse  it's extending the existing logger
    'formatters':{
        'standard':{
        'format':'{levelname} - {asctime} - {message}- {name}-{lineno}- {asctime}- {pathname}- {module}- {funcName}- {filename}- {message}- {process}- {thread}- {threadName}',
        'style':'{',
        }
        # 'simple':{
        #   'format':'{levelname} - {asctime} - {message}- {name}-{lineno}- {asctime}- {pathname}- ',
        #   'style':'{',
        # },
        # 'standard':{
        #   'format':'%(levelname) - %(asctime) - %(message)- %(name)- %(lineno)- %(asctime)- %(pathname)- %(module)- %(funcName)- %(filename)- %(message)- %(process)- %(thread)- %(threadName)',
        # 'style':'%',
        # 'style':'&',
    },
    'handlers':{
        'file':{
        'level':'DEBUG',
        'class':'logging.FileHandler',
        'filename':BASE_DIR / 'logs/log.log', # need create a logs folder in ch48 folder
        'formatter':'standard',
        },
        'console':{
        'level':'DEBUG',
        'class':'logging.StreamHandler',
        'filename':BASE_DIR / 'logs/regular.log', # need create a logs folder in ch48 folder
        'formatter':'simple',
        },
        'rotatingfile':{
            'level':'DEBUG',
            'class':'logging.handlers.RotatingFileHandler',
            'filename':BASE_DIR / 'logs/log.log', # need create a logs folder in ch48 folder
            'max_bytes':1024*1024*100, # 100 MB
            'backup_count':3,
            'formatter':'simple',
        },
        'timebasedfilerotating':{
            'level':'DEBUG',
            'class':'logging.handlers.TimedRotatingFileHandler',
            'filename':BASE_DIR / 'logs/log.log', # need create a logs folder in ch48 folder
            'when':'midnight', # it will create a new log file at midnight
            'interval':1, # it will create a new log file every day
            'backup_count':7, # it will keep 7 log files
            'formatter':'simple',
        },
    },
    'loggers':{
        '':{ # default logger : when logger = logging.getLogger(__name__)
        'handlers':['console'],
        'level':'DEBUG',
        'propagate':False, # it's not propagate to other loggers
        },

        'user':{
        'handlers':['console'],
        'level':'DEBUG',
        },
    }
    }