# Generated by Django 6.0.2 on 2026-02-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='ahmd', max_length=50),
            preserve_default=False,
        ),
    ]
