# Generated by Django 6.0.2 on 2026-02-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comment',
            field=models.TextField(default='No comment', max_length=500),
        ),
    ]
