# Generated by Django 6.0.2 on 2026-02-20 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_profile_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='roll',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
